### ISSUE TITLE
Update grid system (sass)

### ISSUE THREAD

**Issue by svichas** [svichas/essentials.css#1]
essentials.css grid system is made with flex box. Needs update. file: **'src/_grid.sass'**

**Comment by nandomoreirame** [comment]
@svichas Can you explain a little more about what to do?

thanks.

**Comment by svichas** [comment]
Nothing specific. just make essentials.css grid system a little better. more responsive, maybe remove flex etc.

**Comment by bobharley** [comment]
I would like to help on this

**Comment by hostel** [comment]
@svichas I'm made your grid little better #3
